### ISSUE TITLE
Option to Customize Padding

### ISSUE THREAD

**Issue by enesbala5** [anaarkei/zen-floating-toolbar#2]
Hey - thank you for taking the time to build this. It's honestly great.

My main gripe with it however is that it's further away from the borders than the tab section.

![image](https://github.com/user-attachments/assets/e826e979-de84-4343-be89-7e909581376b)

As you can see it looks kind of odd this way.

I would love if we could customize the padding in the setting section, and have the ability to choose what works for us.

Thank you!

**Comment by anaarkei** [comment]
The mod on the store does not use the CSS variable that matches the one used by the tab bar, which is why they do not match like in the screenshot. I think the latest version of the browser changed the variable, which caused this bug. I have fixed this in the latest version of the mod (I will be updating on the store soon).

There is no way, at present, to let users specify the amount of padding, however there are presets that can be enabled using CSS variables. I have added an option, that can be toggled, which will use large padding, and will be used by both the toolbar and the tab bar (this will also be on the store soon).
